"""The short analysis printed under every event: why you might pursue this one,
what it will actually be like, and what you would come away able to do.

Deliberately NOT generated by a language model. Every sentence is composed from
facts the scout already holds — type, fields, cost, effort, selectivity, travel,
your own faculty, deadline pressure — plus a small hand-written knowledge base
describing what each FORMAT involves. That knowledge base describes the format
in general ("a Toastmasters club meets fortnightly and..."), never the specific
event, so there is nothing here that can be fabricated about a particular
opportunity. It is also free, deterministic, and testable.
"""
from __future__ import annotations

import re
from datetime import date
from typing import List, Optional

from models import NOT_STATED, Event

# ---------------------------------------------------------------------------
# What the format is actually like. Written to set expectations honestly,
# including the parts people find unpleasant.
# ---------------------------------------------------------------------------
FORMAT_NOTES = {
    "toastmasters": (
        "A Toastmasters-style club is regular practice, not a contest: members "
        "meet every week or two, one or two give a prepared speech of five to "
        "seven minutes, everyone else takes an impromptu one-to-two-minute "
        "\"Table Topic\", and each speaker gets a spoken evaluation from a "
        "peer. Progress comes from repetition over months rather than from any "
        "single night, and there is usually a membership fee rather than a "
        "ticket price. Low stakes, friendly room, slow and cumulative."),
    "debate": (
        "Competitive debate is adversarial and fast. In the British "
        "Parliamentary format used by most European university circuits, four "
        "two-person teams get the motion about fifteen minutes before they "
        "speak, deliver seven-minute speeches, and take points of information "
        "mid-speech. Judging is on argument quality and rebuttal, not delivery "
        "polish. It rewards quick structured thinking and wide general "
        "knowledge, and it is genuinely uncomfortable at first."),
    "mun": (
        "Model United Nations is role-play under formal rules of procedure: "
        "you represent an assigned country, not your own view, and spend a "
        "multi-day conference caucusing and drafting resolutions. Expect "
        "position papers written in advance, a registration fee, and a strong "
        "social side. Good for negotiation and formal speaking; weaker as "
        "technical evidence on an engineering CV."),
    "pitch": (
        "A pitch competition is three to five minutes in front of judges "
        "followed by hostile questions. The speaking practice is real but "
        "narrow — you rehearse one thing until it is smooth — and the value is "
        "usually the judges' feedback and the room, not the prize."),
    "hackathon": (
        "A hackathon is one to three days of building something demonstrable "
        "in a team, usually ending in a short demo to judges. Sleep is "
        "optional and often skipped. The output is a portfolio artefact and "
        "teammates you will keep running into."),
    "formula_student": (
        "Formula Student is a season, not an event: a year of design, "
        "manufacturing and testing inside a university team, judged on "
        "engineering design and cost as well as track performance. It is the "
        "single most recognised undergraduate credential in automotive and "
        "motorsport recruiting, and it will take several evenings a week."),
    "competition": (
        "A competition compresses a real problem into a fixed window with a "
        "deadline and judges. The result is a rankable line on a CV and "
        "evidence you can work under constraint."),
    "internship": (
        "An internship is the strongest single item an engineering "
        "undergraduate can hold, because it is the only one that demonstrates "
        "sustained work in a professional setting rather than a weekend of it."),
    "summer_school": (
        "A summer school is taught contact time with academics, usually "
        "one to three weeks, often with a certificate and occasionally ECTS. "
        "The teaching is the point; the network is a bonus."),
    "workshop": (
        "A workshop is a few hours of hands-on instruction. Useful for a "
        "specific skill, rarely worth listing on a CV by itself."),
    "conference": (
        "A conference is mostly listening, with the value concentrated in the "
        "breaks. Worth it when the attendee list matters more than the talks."),
    "financial_literacy": (
        "Personal-finance and literacy sessions are introductory by design: "
        "budgeting, compound interest, how instruments and taxes work. They "
        "build judgement you will use for life, but they are not a finance "
        "credential and will not read as one."),
}

_FORMAT_PATTERNS = [
    ("toastmasters", r"toastmaster|clube de oratória|speaking club"),
    ("mun", r"model united nations|\bmun\b|modelo das na[çc][õo]es"),
    ("debate", r"\bdebat(e|ing|es)\b|parliamentary|sociedade de debates"),
    ("pitch", r"pitch (competition|contest|day|night)|elevator pitch"),
    ("formula_student", r"formula student|shell eco-?marathon|baja sae|formula sae"),
    ("financial_literacy", r"literacia financeira|financial literacy|"
                           r"finan[çc]as pessoais|personal finance"),
]

SKILLS = {
    "hackathon": ["rapid prototyping", "working in a team under time pressure",
                  "demoing unfinished work"],
    "competition": ["structured problem solving", "working to a specification",
                    "performing under judging"],
    "internship": ["professional working habits", "an industry reference",
                   "seeing how decisions actually get made"],
    "summer_school": ["technical depth beyond the syllabus",
                      "academic contacts outside Porto"],
    "workshop": ["one concrete tool or technique"],
    "conference": ["a map of who is working on what", "conversational range"],
    "volunteer": ["organising other people", "commitment over time"],
    "masterclass": ["a focused technique from a practitioner"],
}
FIELD_SKILLS = {
    "public_speaking": ["speaking to a room without notes",
                        "structuring an argument live", "handling questions"],
    "economics_literacy": ["reading financial statements and rates",
                           "judging risk and cost over time"],
    "mechanical": ["applied mechanical reasoning"],
    "automotive_motorsport": ["vehicle systems knowledge"],
    "data_ai": ["working with data end to end"],
    "entrepreneurship": ["turning an idea into something presentable"],
    "industrial_ops": ["process and operations thinking"],
    "business": ["commercial framing of a technical problem"],
    "finance_quant": ["quantitative modelling"],
}


def detect_format(ev: Event) -> Optional[str]:
    hay = f"{ev.title} {ev.one_line_summary} {ev.organiser}".lower()
    for key, pattern in _FORMAT_PATTERNS:
        if re.search(pattern, hay):
            return key
    return ev.type if ev.type in FORMAT_NOTES else None


def skills_for(ev: Event) -> List[str]:
    out = list(SKILLS.get(ev.type, []))
    for f in ev.fields:
        out += FIELD_SKILLS.get(f, [])
    seen, uniq = set(), []
    for s in out:
        if s not in seen:
            seen.add(s)
            uniq.append(s)
    return uniq[:4]


def _cost_sentence(ev: Event, cfg: dict) -> Optional[str]:
    price = ev.price_eur()
    free_floor = cfg["cost"].get("never_exclude_below_eur", 50)
    if ev.cost == "funded":
        return ("It is funded, so the cost of going is your time rather than "
                "your money.")
    if ev.cost == "free" or price == 0:
        return None
    if price is None:
        return ("The price is not stated anywhere the scout could find — worth "
                "establishing before you invest any effort in applying.")
    if price <= free_floor:
        return (f"At €{price:g} it is cheap enough that the real cost is the "
                f"{ev.estimated_effort_hours}h, not the ticket.")
    basis = []
    if ev.rewards not in (NOT_STATED, "none stated", ""):
        basis.append(f"it comes with {ev.rewards.replace('_', ' ')}")
    if ev.selectivity in ("competitive", "invite_only"):
        basis.append("entry is selective, which is part of what the line is worth")
    if (ev.prestige_score or 0) >= 4:
        basis.append("the organiser is recognised")
    tail = ("; " + ", and ".join(basis)) if basis else \
           ("; nothing stated justifies that price, so treat it sceptically "
            "unless you can find out what you get")
    return f"It costs €{price:g}{tail}."


def _fit_sentence(ev: Event, cfg: dict) -> str:
    fw = cfg["scoring"]["field_weights"]
    best = max(ev.fields, key=lambda f: fw.get(f, 0.0), default=None)
    weight = fw.get(best, 0.0) if best else 0.0
    label = (best or "").replace("_", " ")
    if "your own faculty" in ev.flags:
        return ("It is run inside your own faculty, which makes it the "
                "cheapest thing on this list to attend and the easiest to "
                "follow up on afterwards.")
    if weight >= 0.85:
        return f"It sits squarely in {label}, one of your highest priorities."
    if weight >= 0.6:
        return f"It is adjacent to your core interests via {label}."
    if best:
        return (f"It is a stretch from your main areas — {label} — so it earns "
                f"its place on breadth rather than direct relevance.")
    return ("Nothing in it matched your stated interests, so it is here on "
            "general merit alone.")


def _timing_sentence(ev: Event, today: date) -> Optional[str]:
    d = ev.days_until_next_deadline
    if d is not None and d <= 7:
        return (f"The deadline is {d} day(s) away, so this is a decision for "
                f"this week rather than a bookmark.")
    if ev.calendar_conflict == "clashes_with_term_time":
        return (f"It falls in term time and costs about "
                f"{ev.estimated_effort_hours}h, so it comes out of study weeks.")
    if ev.calendar_conflict == "near_exams":
        return "It sits close to an exam period — check your own timetable first."
    if ev.intensity in ("heavy", "intense"):
        return (f"At roughly {ev.estimated_effort_hours}h it is a real "
                f"commitment, not an evening.")
    return None


def build_note(ev: Event, cfg: dict, today: date) -> List[str]:
    """Two to five sentences, in the order you would actually want them."""
    lines = []
    fmt = detect_format(ev)
    if fmt and fmt in FORMAT_NOTES:
        lines.append(FORMAT_NOTES[fmt])
    lines.append(_fit_sentence(ev, cfg))
    cost = _cost_sentence(ev, cfg)
    if cost:
        lines.append(cost)
    timing = _timing_sentence(ev, today)
    if timing:
        lines.append(timing)
    if ev.domestic_twin:
        lines.append(f"A Portuguese edition of this is also open "
                     f"({ev.domestic_twin}); compare the two before booking "
                     f"travel.")
    return lines


def annotate(ev: Event, cfg: dict, today: date) -> None:
    ev.analysis = build_note(ev, cfg, today)
    ev.skills_developed = skills_for(ev)
